### ISSUE TITLE
RFC: Empty `case`

### ISSUE THREAD

**Issue by jneen** [opencounter/dentaku#15]
Supersedes: #8 

## Problem

Functions like `IFS(cond, val, cond, val, default)` are not really definable in our current type system, which expects functions to have a statically known number of arguments. However, in #8 we realized that this expression:

```
CASE true
WHEN cond THEN val
WHEN cond THEN val
ELSE default
END
```

has the same semantics. However, this is not an obvious use of the `CASE` form, and it is a bit obtuse to figure out.

## Proposal

This proposal is to introduce a new variant of `CASE` syntax in which the inspected value is simply left out:

```
CASE
WHEN bool_expression THEN result
WHEN bool_expression THEN result
ELSE default
END
```

This syntax form would assert that all the WHEN expressions are boolean, and take the same result type as all result expressions and the default expression. These would be evaluated in order from top to bottom, and short-circuit at the end.

## Concerns

It is possible we need to think about the impact on partial evaluation, similar to AND and OR.

**Comment by jneen** [comment]
cc @joshuabates @linhgoes

**Comment by linhgoes** [comment]
Is the goal of this to avoid having many nested IF and Cases?

**Comment by jneen** [comment]
Closing as we've implemented this
